apiVersion: v2
name: sealed-secrets
description: A Helm chart for Kubernetes
version: 1.0.0
appVersion: "1.16.0"
dependencies:
  - name: sealed-secrets
    version: 2.7.0
    repository: https://bitnami-labs.github.io/sealed-secrets