affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 10
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: bwalia/kisaan-nextjs
  tag: latest
imagePullSecrets:
- name: hh-west-1-docker-registry
ingress:
  annotations: {}
  className: nginx
  enabled: true
  hosts:
  - host: test.kisaan.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  - host: test-www.kisaan.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
probes:
  liveness:
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
  readiness:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
replicaCount: 1
resources: {}
safeEnvFile: AgDKoOxQOEdNUQiW0/w0yKBcPeLLa6/vPbYK0ZEHiju0YpAhz+J88Zfb7DQgCTxMzfjRVb6bMPoYw6UqQp5jyjXtOlXP/uVciGRePZ8Xutu6X/qhbcmErTFoSv5tHh+0FyeP6yZZxoPHEKDrH0VYc0H56SazS0BOCFZPTYHqLS+3kab+bkOgrEMHOypnSvyKdcFFDn9crKHVLdg1e3heb9IIoZW0nGkDOC+ZhAMxLctEVfnTXVMEkvynJIA758F8wHphS8XgC67eRQq1I4htpXExy/76+lwoq/zoUwCrO637oHDXn5z1TyCIc1E+mnjyJciXHR/NMKnFDua1TDB1N+5RMhANcacGndsqA9Od7cRCwui+DFZ2YHUWWzfLPEJHxG1qz61SwKRYEEQ+bWk/ZHRR+YWcUeI3ncB3slyFPfUFCHlKvoHcXov8i1DPMuNiobcwBQv+HTe1QnseUUonj4l25HgX8kJTJgfHqGctV95AuuakTMcPuJ8lT6WcpO2ie0JFoAlONS5YXv5g8ffWf6SRzEdx510yo4ybcjLfEJ1TrarGdEVLZj8B8ZsIgNKbJNWkZeOI/X24NSTgSWqtugwZ+w69xP3vUiANKKeMZAsczvrPqLHEyccQV4GQTK5TduV+u18dbYNENxcO5AlfnY9oazsMoTiGX+5xVXdTlGYAp4aXLttRg+8SHzb21kRXZu/E9Q8QuYGT9lhwILlinWLnD8m9fIYc1lhBe/kHcmJU/d94ng9guRHXqur3qSNG+zpzZYPCfnacWswjH5DjvfkIwiZgfjB8qRenHQl5b4RZHvx4Mofu9viSBGOjqQHG0x+bQx6vRQHF4HPTlLeE5soBysEBeqHwIPSgViIfB/xUNK0TtVdA1pQ+0h2gPpMYHHfhl3+NiwW/pEP4fsIVujIyYjiH6+n0cqBBN1oFlNyUiAdKApgfNP6MHeKFrVDOQV4Y6FMCKlWRt9ZGoi/GEZYsTd45csxAOc6CkGNpGS+mPHKM5l1tgYz1pWn6BrPncGtHoqSd6rs0ntTOQsb0x+3qVfr3qBZePJnohog+6wo1DetkC7Cesn3NxVu1uSq3E+wAiZb+4ba80X+O7wv/52hOUb3JXCh/RDzmVu1OSqrodFwySvBmubXiEBwwc2QThHeGxF0C1DOXDvlbQ84m5h0uvwn51HD9IoOLEvhRYtON+xninf+P1atgzAAwbFsl+8rRJ5zYF55Mo70++jIeKPM9ii/jM+yDB+MgqOh+1khO1lQh6ZujlWh4WYx0dLGe6C0UPN+mNqUzPNQtP/2/H6IPukNklMj6ZNtnzZlv0lZt5FbBf+tQqnweClwX2R9Tls6sip9edEKl7y80gvDo5bIX9eOz76e8//5L2zl3pbFW3dKfGv5O+n3fygOcUpAe9b0i9cokjZX7aFPJWBrl1jg8gQiu6ARRzsNsz5ajo7+aGYuDEuKDmRZ3az9wan+wo/u9sqNwmqadkJkli8Qwf/DqMNDOSVpft1XbHaLveEca+LH05mzSX74uWS2oqPKtI6qCsPGblGcVBomc81CnV6rUCFOM4aR2y+8R0TokkI9Uk2qnoftZ46qYdrZFCk/S5Kchq4qH0pb+tDu+rD92fVWSdI8hF/R+HOn+aDBpj7Vpep26aNOdsEJmCkx8gWKMMMveq+VEYy3xzZtGSB+6ZlMXuhXqsyLdHnfoEsHX2TSmILxif7fZ0nh0T10e5uBeiVm2DJEf+2G0W6c3L2ap/L6KtIfemcScndkUPi7bv3vY6g7bOWmCyXwXzB/Z2hCpjGB3l5GRxdFQyyrxBlHJXnVHBfGhnlbEk3zFT5cFT1bLhOtRRUgEwKY6SzMk8/DPotl8PY1X4gs0zIbFXvSSlvsG3s0WoH0xf9mDmOYfURCOEObv3xisymThEchCxXMpAtPLzWSw54RGmtN/cV6N4G1gT+BgIYS3m5I5FXN8dKrEEYXEGwBVszGi161mhYgUJi5SlT5LqttRlYviwzLN+7SkzldKca4OcKJe9BPx9oplG6hPmhArsZKV2luMTou55zO7gHY6qlsA5D4jD91PU6M/kKryEENwcdeH5oSjtTXyRAyVdaLpYT2t0ZTJTSXt0pdyXKt7UEULtvA4cSHaQmNZ/c7EEBveR8szpi12PLe2wUQQVzTLf3wQrlKxeVlqMG0jy1V0YL/xlRm8D2jx21aDp5yo61gBwnl2irXMF2zQL8xnt1Nwy6Zbzj9m6VbnynNpxXLEEfTbQ3vwfGwQl6uncUre4vbmF3JmykcBmwHS0NvH19CgzkCIGaftdu19YXRIAki9JzebeeAzTu1A51nTrRltUpJF5ZP/Hv6aPVJw+KWyDR6vbmv6+hM9JVP86Ubzwfn1D3LoEG3AavcrxpP7OyxVqoybAbq7rp/YWks3qDyhMEwU2u3agd0mNERqU1Zee914udsyAyv4oVmvsbYr9TNtPlEJLUW4q8piKd1QUF3bBuyT8jjswhByTV1kW/3FppXMZwQZms7wTegj35dqnKe/AeKv/OcIeB5i5lQP50e2Q2f5Nwu0Mj+5duZTCuj1GUiNr6qM9mdivqGdanEsieY2T9mN3+68t3WgjOwi1zdDmVYcHkNSbmhnVM+oXB93C35XfY7d/QczvGX8lHdnkOg2QBWvndlUHGb3CuITDiiPFF2ebqRMNXKNIAxggOM7EgYQ85KRTOb4fpLFJDBUgCVXQyyH4T7yDa9BrKypbY7De6KhXjNTT1SwelqxDYeol5gh2uqjzorar33KvO+U9S8xv3z+/2rl4mTr4H9w4kN939dUUvAkGoszkG/DOinlFGVVXsxsbrtF+dTKiFCbSHc7mNA4GYEQjJ+9HSG3TqmFNgr4oupjXHW7V8qLgMm0yJYXK75CRt+0VHvy9jJ2gJhGlDkQjYxV85ZWVDGpOeCmn1z6A4i3YBmdFNCuh+La6NuSb4CXq8Gynd5cVC6m0cer+WpV/Sv7DWOakLtoeO62P2VWIqBEeN2VcLy+cshDhAGXQ0CYCw/JJZSsta+R18yrAkD92oLTiA9M2vjIotHdVXciC0isuFrQ62qSlJjk3rc/d+/TFGzJY0gOBntUx39Wi07R1JFcqUYbg9EVqLrUwTqcK3yex2++Tcdc72AvtPkIvbyLO3PfFk1HGRz2DxN4lEwxQrcMlq7jeQpdizBwkWa1cdgQmEszRIesYuqiNNUYCm5InYRRqAwjUZmFx2ViXX5rhgGTn2XUbrq5weKUaq545YknDFpLr4YVr4DCqsafXDQNcCKwbCr/pnm5DFkTwY5B95ZOUasp7W2lplTp/HO+WGmMlp0IheGWUYdJKz4+DmWG21ba1fw7UBzPkHk5LVzk8hBUCmjA
securityContext: {}
service:
  namespace: test
  port: 3000
  targetPort: 3000
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''
tolerations: []
volumeMounts: []
volumes: []
