# Development Dockerfile
FROM node:22-alpine AS development

ENV NODE_ENV=development
ENV TAG=latest

# Install dependencies for development
RUN apk add --no-cache libc6-compat

# Add a work directory
WORKDIR /app

# Cache and Install dependencies
COPY kisaan-next/package.json .
#COPY yarn.lock .

RUN apk add curl

RUN npm i

# Copy app files
COPY kisaan-next/ .

#   RUN npm install vite -g
#   This works here but not in dockerfile RUN vite build --mode staging so replacing with npm build
#   RUN npm run build

# Expose port
EXPOSE 3000

# Start the app
CMD [ "npm", "run", "dev" ]