# Development Dockerfile
FROM node:22-alpine

ENV TAG=latest
ENV NODE_ENV=production
# Install dependencies for development
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy package files
# COPY opsapi-ecommerce/opsapi-ecommerce/package*.json ./

# Install all dependencies (including dev dependencies)
RUN npm ci

# Copy source code
# COPY opsapi-ecommerce/opsapi-ecommerce/Dockerfile/. ./

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "run", "start"]
